cars/urls.py
from django.urls import path
from . import views


app_name = 'cars'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('detail/<int:pk>/', views.DetailView.as_view(), name='detail')
]

project2/urls.py
from django.contrib import admin
from django.urls import path, include


admin.site.site_title = '車両管理システム'
admin.site.site_header = '車両管理システム' 
admin.site.index_title = 'メニュー'


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cars.urls')),
]

cars/models.py
from django.db import models
from django.utils import timezone


class Insurance(models.Model):
    start_time = models.CharField('開始時期', max_length=100)
    end_time = models.CharField('終了時期', max_length=100)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return f'{self.start_time} ~ {self.end_time}'


class Area(models.Model):
    name = models.CharField('使用地域', max_length=10)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return self.name


class Car(models.Model):
    area = models.ForeignKey(
        Area, verbose_name='地域', on_delete=models.PROTECT
    )
    number = models.CharField('車番', max_length=30)
    chassis_number = models.CharField('車台番号', max_length=30)
    start_use = models.CharField('使用開始', max_length=40, blank=True)
    insurance_period = models.ForeignKey(
        Insurance, verbose_name='保険開始時期', related_name='insurance_1', on_delete=models.PROTECT
    )
    insurance_number = models.CharField('保険証番号', max_length=50)
    comment = models.TextField('コメント', max_length=255, blank=True)
    created_at = models.DateTimeField('日付', default=timezone.now)

    def __str__(self):
        return f'使用エリア：{self.area}, 車番：{self.number}'

cars/views.py
from django.db.models import Q
from django.views import generic
from .models import Car


class IndexView(generic.ListView):
    model = Car
    paginate_by = 15

    def get_queryset(self):
        queryset = Car.objects.all()
        keyword = self.request.GET.get('keyword')
        if keyword:
            queryset = queryset.filter(
                Q(number__icontains=keyword)| Q(area__name__icontains=keyword) | Q(insurance_period__end_time__icontains=keyword)
            )

        return queryset

class DetailView(generic.DetailView):
    model = Car

cars/templates/cars/base.html
<!doctype html>
<html lang="ja">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>車両管理システム</title>
  </head>
  <body>
  {% if not user.is_active %}
  <h3 style="text-align: center;">こちらから<a href="admin/">管理サイト</a>へログインしてください</h3>
  {% endif %}
  {% if user.is_active %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'cars:index' %}">車両管理システム</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'cars:index' %}">一覧 <span class="sr-only">(current)</span></a>
      </li>
      {% if user.is_superuser %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:cars_car_add' %}" target='_brank'>車両追加</a>
      </li>
      {% endif %}
    </ul>
    <form class="form-inline my-2 my-lg-0" method="GET" action="#">
      <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search" name="keyword">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
    </form>
  </div>
</nav>

    <div class="container">
        {% block content %}
        {% endblock %}
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    {% endif %}
  </body>
</html>

cars/templates/cars/car_detail.html
{% extends 'cars/base.html' %}

{% block content %}
<table class="table table-bordered mt-5">
  <thead class="thead-dark">
    <tr>
      <th>項目</th>
      <th>内容</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>車番</td>
      <td>{{ car.number }}</td>
    </tr>
    <tr>
      <td>使用県</td>
      <td>{{ car.area }}</td>
    </tr>
    <tr>
      <td>車台番号：</td>
      <td>{{ car.chassis_number }}</td>
    </tr>
    <tr>
      <td>使用開始時期：</td>
      <td>{{ car.start_use }}</td>
    </tr>
    <tr>
      <td>保険期間</td>
      <td>{{ car.insurance_period }}</td>
    </tr>
    <tr>
      <td>保険証番号</td>
      <td>{{ car.insurance_number }}</td>
    </tr>
    <tr>
      <td>コメント</td>
      <td>{{ car.comment | linebreaksbr }}</td>
    </tr>
  </tbody>
</table>

{% endblock %}

cars/templates/cars/car_list.html
{% extends 'cars/base.html' %}

{% block content %}
<table class="table mt-3">
  <thead class="thead-dark">
    <tr>
      <th>車番</th>
      <th>使用県</th>
      <th>使用開始時期</th>
      <th>保険期間</th>
    </tr>
  </thead>
  <tbody>
  {% for car in car_list %}
    <tr>
      <td><a href="{% url 'cars:detail' car.pk %}">{{ car.number }}</a></td>
      <td>{{ car.area }}</td>
      <td>{{ car.start_use }}</td>
      <td>{{ car.insurance_period }}</td>
  {% endfor %}
  </tbody>
</table>

{% include 'cars/page.html' %}

{% endblock %}

cars/templates/cars/page.html
{% load mytag %}
<nav aria-label="Page navigation">
  <ul class="pagination">
 
      {% if page_obj.has_previous %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.previous_page_number %}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
        </a>
      </li>
      {% endif %}
    
      {% for link_page in page_obj.paginator.page_range %}
        {% if link_page == page_obj.number %}
          <li class="page-item active">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% else %}
          <li class="page-item">
            <a class="page-link" href="?{% url_replace request 'page' link_page %}">
              {{ link_page }}
            </a>
          </li>
        {% endif %}
      {% endfor %}
    
      {% if page_obj.has_next %}
        <li class="page-item">
        <a class="page-link" href="?{% url_replace request 'page' page_obj.next_page_number %}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
        </a>
      </li>
      {% endif %}
    
  </ul>
</nav>